directory: /mnt/nas/music/archive
library: /mnt/nas/music/archive/beets.blb
paths:
    default: Albums/$albumartist/($year) $album%aunique{}/$track - $title
    singleton: Singles/$artist/$title
    comp: Compilations/$album%aunique{}/$track - $title
plugins: replaygain fetchart smartplaylist mpdupdate
replaygain:
    backend: gstreamer
    overwrite: yes
smartplaylist:
    relative_to: /mnt/nas/music/archive/
    playlist_dir: ~/.config/mpd/playlists/
    playlists:
        - name: all.m3u
          query: ''

