location:
    source_directories:
        - ~/path/to/backup/dir/

    repositories:
        - ~/path/to/repo/dir/

    exclude_patterns:
        - .DS_Store

storage:
    encryption_passphrase: <repo_password>

    compression: lz4

retention:
    keep_daily: 7

    keep_weekly: 4

    keep_monthly: 6

    keep_yearly: 1

consistency:
    checks:
        - repository
        - archives

    check_last: 3

