directory: {PATH TO MUSIC DIR}
library: {PATH TO MUSIC DIR}/beets.blb
paths:
    default: Albums/$albumartist/($year) $album%aunique{}/$track - $title
    singleton: Singles/$artist/$title
    comp: Compilations/$album%aunique{}/$track - $title
plugins: replaygain fetchart
replaygain:
    backend: gstreamer
    overwrite: yes

