directory: {PATH TO MUSIC DIR}
library: {PATH TO MUSIC DIR}/beets.blb
paths:
    default: Albums/$albumartist/($year) $album%aunique{}/$track - $title
    singleton: Singles/$artist/$title
    comp: Compilations/$album%aunique{}/$track - $title
plugins: replaygain fetchart follow plexupdate
replaygain:
    backend: gstreamer
follow:
    email: {MUSPY LOGIN DETAILS HERE}
    password: {MUSPY LOGIN DETAILS HERE}
    userid: {MUSPY LOGIN DETAILS HERE}
    auto: yes
plex:
    host: {LOCAL PLEX IP}
    port: 32400
    library_name: Music

